### ISSUE TITLE
render more private POI icons lighter

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1012]
Parking has amenity-points.mss#L172

```
[access != ''][access != 'yes'] {
   marker-opacity: 0.33; 
```

This works, as the marker is in SVG format. I think this could be extended. It is better to change the icon SVG format, but even PNGs can have point-opacity:
- [x] leisure_playground (opacity #1191, SVG icon: #1177 merged)
- [x] amenity_recycling (opacity #1191, SVG icon: #1175 merged)
- [ ] amenity_toilets (SVG icon: #1328 merged)
- [x] <s>natural_cave_entrance (for security reasons) (opacity #1262 btw the cave entrace icon is in another mss-file than its name)</s> (rejected)

less important
- [ ] tourism_picnic_site
- [ ] leisure_picnic_table
- [ ] amenity_drinking_water

and perhaps:
- [ ] tourism_museum (SVG icon: #1174 merged)
- [ ] historic_archaeological_site
- [ ] amenity_library (SVG icon: #1228 )

For parking the name has another text color (hard coded, and not defined btw) which has to be decided as well.
- [ ] A logic the other way round could be implemented for barrier nodes.

**Comment by mkoniecz** [comment]
So toilets and archaeological site are now waiting for SVG icons.

natural=cave_entrance is problematic, as it is not clear what access on it means. It may declare whatever cave entrance is accessible or is it about cave? How should one tag cave entrance that is reachable, but further travel is impossible (door, bars etc)?

Maybe definition is hidden somewhere on OSM wiki, but as it is not intuitive big part of tags would ignore it anyway.

**Comment by nebulon42** [comment]
IMO access on the cave entrance means the cave. Reachability has to be represented on ways towards the entrance. If there are none then everybody would have to judge for his/her own if it would be dangerous/impossible to reach the entrance.

**Comment by HolgerJeromin** [comment]
Most "private" museums i found requires pre-registration. IMO a very valid reason to render them with opacity.

**Comment by nebulon42** [comment]
There is now a icon proposal for library (see #1228).

**Comment by pnorman** [comment]
> This works, as the marker is in SVG format. I think this could be extended to at least, but the icon has to be changed to SVG format:

There is no need to change the icons to SVG for opacity. See [point-opacity](https://github.com/mapbox/carto/blob/master/docs/latest.md#point-opacity-float).

SVG gains us two things over PNG

1. Improved print and high-DPI tile sharpness. The latter does not impact tile.openstreetmap.org
2. The ability to set the icon colour in the MSS.

**Comment by HolgerJeromin** [comment]
pnorman: thanks for your explanation. updated

**Comment by tilmanb** [comment]
I propose to use point-opacity and text-opacity with a value of 0.55 because that looks nice. Also, no new symbols are needed.

**Comment by dieterdreist** [comment]
2015-01-05 12:56 GMT+01:00 Holger Jeromin <notifications@github.com>:

> Most "private" museums i found requires pre-registration. IMO a very valid
> reason to render them with opacity.



I'd not render them at all on a general purpose map, assuming that
"private" is not about ownership but access. Ownership shouldn't matter,
there are lots of "private" museums that are in no respect different to
publicly owned museums from a visitor's point of view. Think of the vatican
museum (owned by the roman catholic church), the Guggenheim Museum, the
Mercedes Benz Museum, etc., all privately owned.

**Comment by kocio-pl** [comment]
@dieterdreist I don't agree with it, let's look at [this example](http://www.openstreetmap.org/#map=17/48.24909/14.27990): if we stop rendering private playgrounds, we would have strange holes. The same is true for private parkings. One can argue that this is the same even with nodes on sufficient zoom level (z>=19). 

I guess the rule of thumb should be like this: private features should be less visible than public ones, but they should not be hidden, especially if they are part of the landscape.

**Comment by kocio-pl** [comment]
Anyone willing to prepare the code?

**Comment by Tomasz-W** [comment]
I checked few OSM Wiki pages with tags tables to make a complete list of lighter icon candidates. I also though about tags mentioned above:
* amenity=toilets -> I think toilets shouldn't be considered here, because they have restricted access by it's nature, so making difference basing on access=* tag could make mess in this situation
* leisure=picnic_table -> tagging whole tourism=picnic_site with access=* is much more popular

My candidates:
* amenity=bbq
* amenity=bicycle_parking
* amenity=bicycle_repair_station -> after https://github.com/gravitystorm/openstreetmap-carto/issues/3069
* amenity=drinking_water
* amenity=charging_station
* amenity=shelter
* tourism=picnic_site
* tourism=wilderness_hut

**Comment by kocio-pl** [comment]
> I think toilets shouldn't be considered here, because they have restricted access by it's nature

I don't think so, there are different toilets. Some are paid, some are free, some are closed, some are opened all the time (imagine for example toilets on the beach or mobile toilets).

**Comment by jragusa** [comment]
First tries:

`amenity=bbq`
https://www.openstreetmap.org/node/1062462954
![private_bbq](https://user-images.githubusercontent.com/9897203/48803991-c03a2e00-ed13-11e8-9c03-847e3def7ad7.png)

`amenity=bicycle_repair_station`
https://www.openstreetmap.org/way/266000780
![private_bicycle_repair](https://user-images.githubusercontent.com/9897203/48803986-bc0e1080-ed13-11e8-9af6-fa5152ff6c9e.png)

`amenity=drinking_water`
https://www.openstreetmap.org/node/5275971271
![private_drinking_water](https://user-images.githubusercontent.com/9897203/48804379-bb29ae80-ed14-11e8-9808-e9eec0f249c7.png)

**Comment by jragusa** [comment]
Example with a camp site:
`amenity=shower`, `amenity=toilets` and `leisure=playground`
https://www.openstreetmap.org/way/343862313
![private_shower](https://user-images.githubusercontent.com/9897203/48832582-c4993200-ed79-11e8-8bd4-b4ea4e94e1d8.png)

`amenity=charging_station`
https://www.openstreetmap.org/node/5996039033
![private_charging_station](https://user-images.githubusercontent.com/9897203/48832935-98ca7c00-ed7a-11e8-9579-aea8852e213e.png)

`amenity=shelter`
https://www.openstreetmap.org/way/426143872
![private_shelter](https://user-images.githubusercontent.com/9897203/48834688-b13c9580-ed7e-11e8-903d-01638c12817b.png)

`tourism=picnic_site`
https://www.openstreetmap.org/node/771443110 (forest background)
![private_picnic](https://user-images.githubusercontent.com/9897203/48833718-4b4f0e80-ed7c-11e8-8948-1cdc8db71be4.png)
https://www.openstreetmap.org/node/392096251
![private_picnic2](https://user-images.githubusercontent.com/9897203/48833917-b6004a00-ed7c-11e8-89b1-c9cbb7aebfc4.png)

`tourism=wilderness_hut`
https://www.openstreetmap.org/way/137043135
![private_wilderness_hut](https://user-images.githubusercontent.com/9897203/48834110-3de65400-ed7d-11e8-9e5f-bcaac0047fd2.png)

`leisure=fitness_station`
https://www.openstreetmap.org/way/601801826
![private_fitness_station](https://user-images.githubusercontent.com/9897203/48834320-cfee5c80-ed7d-11e8-9cd2-5a0c04ae19fa.png)

**Comment by Adamant36** [comment]
I really like this idea. Is it the same lightness as private parking though? Comparing the test of wilderness hut to private parking, it seems a little lighter for some reason. Maybe its the tone of blue or something.

**Comment by jragusa** [comment]
`leisure=picnic_table`
https://www.openstreetmap.org/node/4456465161
![private_picnic_table](https://user-images.githubusercontent.com/9897203/48835149-c9f97b00-ed7f-11e8-9d31-949f89a70b35.png)

**Comment by jragusa** [comment]
Few questions:
* @kocio-pl some text POI are scattered into `amenity-points`. Can I group them into a more uniform list ? for example `shower`, `bbq` and `bicycle_repair_station` are grouped together and `drinking_water`, `picnic_table` and` picnic_site` are in an other one.
* Is that ok if there is no label for `amenity=toilets` ?

**Comment by matkoniecz** [comment]
> some text POI are scattered into amenity-points. Can I group them into a more uniform list

It should be OK to reoerder them if that makes code more logical, but it would be preferable to do it in a separate commit (in first commit reorder entries, in second add handling of access tag)

**Comment by kocio-pl** [comment]
Order of many items seems to be more or less random, so grouping is possible when they have something in common. Just remember to not group things too heavily, since it makes any future code changes much harder and error prone.

> Is that ok if there is no label for amenity=toilets ?

What do you mean, not rendering them if the name is tagged? Why would you like to do that?

**Comment by jragusa** [comment]
@matkoniecz I will create a new branch to have a clear commit list for the PR
@kocio-pl I do not want to add label to `amenity=toilets`. I just noticed they do not have a label while `amenity_shower` does for example. If it's ok I will not change this.

If there any other POI to include into the list ?

**Comment by Tomasz-W** [comment]
* amenity=toilets
* tourism=picnic_site
* leisure=picnic_table
* amenity=drinking_water
* amenity=bicycle_parking
* amenity=bbq
* amenity=bicycle_repair_station
* amenity=charging_station
* amenity=shelter
* tourism=wilderness_hut
* leisure=fitness_station

@jragusa I would add these ones too:
* amenity=waste_basket
* amenity=waste_disposal
* leisure=firepit

and consider:
* amenity=bench -> I'm not sure about this one, but if we are going to include picnic tables, then benches propably should be included too (or we exclude both of them)

**Comment by Adamant36** [comment]
There's a lot of private benchs in courtyards, in front of apartment complexes, outside of motels etc. I would say its worth adding them. Same for picnic tables. I wonder bicycle repair stations though. I was under the impression that they are a publically usable utility. Plus, the tag doesnt come up in the combinations for access=private on TagInfo.

**Comment by jragusa** [comment]
@Tomasz-W `amenity=bicycle_parking` is already supported. I include `amenity=waste_*` and `leisure=firepit`
@Adamant36 `amenity=bench` added

I'm preparing the PR for this issue using a new branch to clean the commit list

**Comment by jragusa** [comment]
@Adamant36 it's not clear for now but I think by topic and then alphabetically

**Comment by HolgerJeromin** [comment]
> amenity=bicycle_parking is already supported. I include amenity=waste_* and leisure=firepit

Perhaps private waste_baskets should (not get mapped and) not be rendered.

**Comment by kocio-pl** [comment]
No matter what will be rendered and how, I guess everything that is visible on the ground can be mapped.

**Comment by Adamant36** [comment]
I don't think just because something is private doesn't mean it shouldn't be mapped. There's plenty of none public places that have private, invite only, events where it would still be useful if someone attending a function there could look at the map to find out where a bathroom, wastebasket, or bench is located.

**Comment by matkoniecz** [comment]
Please, let's avoid discussing this topic here. It is vastly preferable to discuss it on talk/tagging (or look through archives, it was discussed at least once) and summarize it on OSM wiki (if it was not done already).

**Comment by HolgerJeromin** [comment]
What about restaurants/fast food?
https://www.openstreetmap.org/node/4364724819
You can not eat there same as in a city centre

Same with a restaurant inside an industrial complex or university campus.
