### ISSUE TITLE
transition to SVG icons

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1165]
I think most will agree that moving all icons to SVG is beneficial (line and pattern symbolizers will have to wait for the transition to Mapnik 3.0). This issue is intended to gather ideas how the transition could work. Issues #632, #658 and #659 are related.

As pointed out by @math1985 in #659 there are currently several efforts for icon repositories. While a central repository is a good idea, we might have to alter icons before using them here and hence not every icon might be useful for each project. So should we create our own repository or just keep track of the icons we include?

https://github.com/twain47/Open-SVG-Map-Icons is a good starting point for a repository, but for me it is not clear what its current status is. Is it still active? While the icons are very good, I also have the impression that some are too complex for small sizes and some have to be altered to be used in this project. I don't follow the puristic view on SVG code of @pnorman regarding Inkscape (I might be wrong on that, please correct me), but still think that code quality matters a bit here (file size).

I'm not sure what the best approach might be. SJJB icons are a good starting point, but some will require alteration or even re-drawing for using them with CartoCSS (e.g. colouring). So I think we cannot use them directly. Should we fork the repository and evolve it further for using the icons with ths project? I would be up for maintaining an icon repository, but this might be overkill and maybe we should concentrate on the icons we will really use.

repository for my icons: https://github.com/nebulon42/osmic

declined (just for reference)
`amenity=car_sharing` (~~#1283~~) - removed in #1901 

completed
- [x] `amenity=hospital` (#1169)
- [x] `amenity=pharmacy` (#1169)
- [x] `amenity=atm` (#1171)
- [x] `amenity=bank` (#1171)
- [x] `tourism=museum` (#1174) 
- [x] `amenity=recycling` (#1175)
- [x] `leisure=playground` (#1177)
- [x] `amenity=place_of_worship` (#1185)
- [x] `amenity=bar` (#1188)
- [x] `amenity=pub` (#1188)
- [x] `amenity=cafe` (#1188)
- [x] `amenity=biergarten` (#1188)
- [x] `amenity=fast_food` (#1188)
- [x] `amenity=restaurant` (#1188)
- [x] `amenity=cinema` (#1211)
- [x] `shop=bakery` (#1212)
- [x] `tourism=camp_site` (#1218)
- [x] `amenity=police` (#1220)
- [x] `amenity=fire_station` (#1220)
- [x] `amenity=embassy` (#1235)
- [x] `amenity=picnic_table/picnic_site` (#1240)
- [x] `historic=memorial` (#1241)
- [x] `amenity=theatre` (#1254)
- [x] `amenity=drinking_water` (#1256)
- [x] `amenity=prison` (#1259)
- [x] `shop=bicycle` (#1281)
- [x] `amenity=bicycle_rental` (#1282)
- [x] `amenity=fuel` (#1284)
- [x] `man_made=mast` (#1324 ~~#1304~~)
- [x] `amenity=toilets` (#1328 ~~#1178~~)
- [x] `shop=car_repair` (#1377)
- [x] `shop=doityourself`(#1380)
- [x] `shop=florist` (#1381)
- [x] `shop=hairdresser` (#1382)
- [x] `man_made=lighthouse` (#1385)
- [x] `tourism=hotel` (#1389)
- [x] `tourism=hostel`(#1390)
- [x] `tourism=motel` (#1426)
- [x] `amenity=courthouse` (#1477)
- [x] `highway=bus_stop` (#1517 ~~#1478~~)
- [x] `historic=archaeological_site` (#1518)
- [x] `tourism=caravan_site` (#1468)
- [x] `leisure=water_park` (#1559)
- [x] `power=generator`with `generator:source=wind` (#1476)
- [x] `man_made=water_tower` (#1519)
- [x] `tourism=viewpoint` (#1572)
- [x] `man_made=windmill` (#1574)
- [x] `amenity=emergency_phone` (#1606)
- [x] `amenity=telephone` (#1607)
- [x] `railway=subway_entrance` (#1521)
- [x] `amenity=post_office` (#1702 ~~#1558~~)
- [x] `amenity=post_box` (#1702 ~~#1558~~)
- [x] `highway=ford` (#1625)
- [x] `natural=cave_entrance` (#2048)
- [x] `amenity=shelter` (#2042)
- [x] `tourism=information` (#2049) (should wait until subtypes of `information=*` can be rendered)
- [x] `amenity=library` (#2147 ~~#2050~~ ~~#1228~~)
- [x] `shop=department_store` (#2243)
- [x] `leisure=slipway` (#2744)
- [x] `amenity=bus_station` (#2754 ~~#2047~~ ~~#1478~~)
- [x] `tourism=alpine_hut` (#2754)
- [x] `tourism=chalet` (#2754)
- [x] `leisure=golf_course` (#2754)
- [x] `tourism=guest_house` (#2754)
- [x] `leisure=miniature_golf` (#2754)
- [x] `shop=butcher` (#2754 ~~#1539~~ ~~#1379~~)

**Comment by HolgerJeromin** [comment]
Could you please add amenity=library to your list?

**Comment by nebulon42** [comment]
Added it. The initial idea was to have only already proposed icons in the list. Of course the plan is to move all icons to SVG (where possible).

**Comment by nebulon42** [comment]
@math1985 @matkoniecz @pnorman Just to let you know, that I have changed my approach regarding icon padding, halos etc. Now only the source files (14x14px) are in my repository. An export script [export.py](https://github.com/nebulon42/osmic/blob/master/tools/export.py) takes care of adding padding, halos, shields etc.

In theory this means that we could move from the 16px canvas with included 1px padding to the pure 14px canvas without padding. This would allow to (possibly) decrease text-dy a little bit and also more space for close icons. Maybe the icons would be too close then, this has to be tested.

What is your opinion on this?

**Comment by math1985** [comment]
As far as I know, the algorithm that checks for clashes only looks at pixels that are actually being used, so I don't think this allows us to decrease text-dy or other distances. Correct me if I'm wrong though!

**Comment by matkoniecz** [comment]
@math1985 

> algorithm that checks for clashes only looks at pixels that are actually being used

I am not sure. Increasing halo that prevented appearance of nearby icons forced also increase of text-dy, so I am not really sure what counts as used pixel.

**Comment by math1985** [comment]
I think the halo consisted of white pixels, which is different from transparent pixels in SVG. But I'm not sure either.

**Comment by nebulon42** [comment]
I will run a test on this.

**Comment by nebulon42** [comment]
My simple test confirmed @math1985's assumption in https://github.com/gravitystorm/openstreetmap-carto/issues/1165#issuecomment-96635625.

**Comment by nebulon42** [comment]
Just to let everybody know that I will take a break from proposing new icon PRs for the time being. There has been an abundance of icon PRs lately and this might have been a bit too much, also for me. So this is my contribution to drop a gear on the subject. This is not a "bye" message.

**Comment by matkoniecz** [comment]
@nebulon42 Thanks for all contributed icons!

**Comment by gravitystorm** [comment]
@nebulon42 And thanks from me too. You have spent more time than most people working with high-zoom level situations, so if you have other non-icon suggestions for us, we'd appreciate your help there too.

**Comment by math1985** [comment]
@nebulon42 Thanks from me as well!

**Comment by daganzdaanda** [comment]
Thank you @nebulon42 , you have really earned a holiday! Just look at those "Merged" batches upthread! 8-O

**Comment by nebulon42** [comment]
Thanks all for feedback and support! ;)

**Comment by kocio-pl** [comment]
shop=department_store [can be checked](https://github.com/gravitystorm/openstreetmap-carto/pull/2243) already.

**Comment by nebulon42** [comment]
done

**Comment by kocio-pl** [comment]
Completed with #2754 at last, thanks everybody! Now we have only to convert some remaining patterns (#2045).

**Comment by math1985** [comment]
Great work everybody!
