### ISSUE TITLE
Porting some french-style solutions [meta-issue]

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1402]
I'd like to have multiple French-style ( http://tile.openstreetmap.fr/ ) solutions, which I consider good, in the osm-carto. I don't know if that's always technically feasible, because I'm not sure what infrastructure are they using ( https://github.com/osm-fr/layers-mapnik-styles maybe?) and if the license is compatible, but maybe sometimes it would be just simple code porting. We already have French-style tree rendering issue ( https://github.com/gravitystorm/openstreetmap-carto/pull/978 ), so I want more of their good stuff.

This should be cut into specific issues eventually, but here we can identify them at general level and make early decisions before flooding the board with multiple issues.

I. [Low zoom level](https://github.com/gravitystorm/openstreetmap-carto/issues/1125)
- [ ] 1. At z3 there could be continents and country labels with some large natural areas like sands/forests/ice in the background
- [ ] 2. At z4 the same as z3, but with rather strong national borders (still not perfect, but visible better than currently in osm-carto, where it's cluttered with states borders), black dots for capitals and some big islands names
- [ ] 3. At z5 the same as z4, and more: all the countries (borders+name) with geographical features, capitals are bolded and some bigger cities are visible too, plus there are subdivisions visible (in some countries borders are visible, in some other just the states names)
- [ ] 4. At z6 the same as z5, but no more country names, more cities and some states visible (maybe we could try put more states with their capitals instead of smaller cities - https://github.com/gravitystorm/openstreetmap-carto/issues/1391)
- [ ] 5. The country and state labels are smartly placed (`text-label-position-tolerance`), so they don't overlap city labels - especially capitals

II. Middle/high zoom level
- [ ] 1. The country's capital name is bold up to z10 and then goes italic up to z14
- [ ] 2. Railway/metro stations names are always visible (>=z14) and have a line breaks if too long
- [ ] 3. [Add realistic Sports Field Marking for pitches](https://github.com/gravitystorm/openstreetmap-carto/issues/1126)

III. High zoom level
- [ ] Better name label placing on buildings (see https://github.com/gravitystorm/openstreetmap-carto/issues/1661)

POI icons we could use:
- [x] 1. Shoes shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1404)
- [x] 2. Photo/photo studio shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1405)
- [x] 3. Furniture shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1406)
- [x] 4. Alcohol/beverages shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1407)
- [x] 5. Optician shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1408)
- [x] 6. Travel agency (see https://github.com/gravitystorm/openstreetmap-carto/issues/1409)
- [x] 7. Greengrocer (see https://github.com/gravitystorm/openstreetmap-carto/issues/1410)
- [x] 8. Laundry/Dry cleaning shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1411)
- [x] 9. Mobile phone shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1412)
- [x] 10. Copy shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1413)
- [x] 11. Toys shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1414)
- [x] 12. Jewelry shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1415)
- [x] 13. Computer shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1416)
- [x] 14. Fishmonger/seafood shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1417)
- [x] 15. Hi-Fi shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1418)
- [x] 16. Motorcycle shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1419)
- [x] 17. Musical instruments shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1420)
- [x] 18. Kiosk shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1459)
- [x] 19. Interior decoration shop (see https://github.com/gravitystorm/openstreetmap-carto/issues/1406)

**Comment by pnorman** [comment]
> I don't know if that's always technically feasible, because I'm not sure what infrastructure are they using ( https://github.com/osm-fr/layers-mapnik-styles maybe?) 

https://github.com/cquest/osmfr-cartocss

> if the license is compatible,
Yes, we're both using CC0

The main technical difference is they have a database with hstore, which we don't have yet.

**Comment by pnorman** [comment]
cc @cquest

It would be nice if we could pull commits from one project to the other. Don't know if it's feasible. For reference, the diffstats are +10k -5k one way and +18k/-2k.

**Comment by cquest** [comment]
Pick all the cherries you want ;)

When I forked and started add my own stuff, I was not familiar with git.
I'm a bit more now but not an expert.

For the low level zooms, I'm planning to rework on it, to speed up
rendering.
I'm not using natural earth data or any other data, only OSM one.
I'm also using a pre-rendered landcover tiff rendered at zoom 8 and down
sampled for zoom 0-7.


Le 18/03/2015 19:17, Paul Norman a écrit :
>
>     I don't know if that's always technically feasible, because I'm
>     not sure what infrastructure are they using (
>     https://github.com/osm-fr/layers-mapnik-styles maybe?)
>
> https://github.com/cquest/osmfr-cartocss
>
>     if the license is compatible,
>     Yes, we're both using CC0
>
> The main technical difference is they have a database with hstore,
> which we don't have yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1402#issuecomment-83107405>.
>

-- 
Christian Quest - OpenStreetMap France

**Comment by nebulon42** [comment]
Regarding introducing new SVG shop icons (if desired) I think we should not add new SVG icons that are not pixel-aligned. And I don't say this because I would want to design all of them myself.

I'm also not sure if "flooding in" new shop icon tickets will increase the likelihood of them being introduced, just a thought.

**Comment by pnorman** [comment]
We added generic shop icons to avoid having to add new icons for every shop. I'm considering if the 16 new issues should be closed.

**Comment by kocio-pl** [comment]
@nebulon42: My feeling is that they are good enough for me on French OSM (I don't know if they are pixel-aligned so call it a blind test of quality), so I prefer having them as they are and then correcting/replacing if not satisfactory for anyone else.

**Comment by kocio-pl** [comment]
@pnorman: I thought generic icon was introduced to avoid giving too high visibility to "not correct" shop types and make mappers try harder than "shop=yes/whatever" and I consider it smart move.

But what is the real problem with adding more (even "correct") icons? Is it purely technical, political or practical maybe?

**Comment by math1985** [comment]
> We added generic shop icons to avoid having to add new icons for every shop. I'm considering if the 16 new issues should be closed.

Personally I would be happy with adding more icons. I have never fully understood the argument against adding more icons, but maybe @pnorman or @gravitystorm can repeat the argument once more (perhaps in #660).

By the way, I think this topic is very useful, thanks @kocio-pl for opening it!

**Comment by matkoniecz** [comment]
I also would be happy with adding new, clearly recognizable icons for popular shops (2000+ uses) that are well defined without tagging conflicts (no icons for shop=seafood and shop=fishmonger) and have a definition on wiki.

**Comment by kocio-pl** [comment]
@nebulon42:
> I'm also not sure if "flooding in" new shop icon tickets will increase the likelihood of them being introduced, just a thought.

Why so cautious? I also don't think it would at all! 

Please don't treat me like project spammer or what. It was only having the icons that are ready to be used which made me think it's worth creating all the tickets. I really appreciate the time of developers spend on making rendering better (including you!), so I try to open the tickets only when I'm sure there are strong merits to do so. And this one was no other - just incidentally this time I had a lot of such (IMO!) strong cases.

Maybe I made it too fast - sorry - but after @pnorman said no single word against them and @cquest gave us the green light, I thought now we're on a safe ground.

**Comment by nebulon42** [comment]
Relax, I didn't say anything about Spam.

**Comment by dieterdreist** [comment]
2015-03-19 0:28 GMT+01:00 math1985 <notifications@github.com>:

> Personally I would be happy with adding more icons. I have never fully
> understood the argument against adding more icons




I agree. I believe the reluctance towards adding more icons is grounded in
the idea to possibly add a legend for every signature and every icon, and
the more you have, the more improbable this gets (or simply unclear). I
believe those shop icons can be designed in a way that they are understood
alone by their iconography (the colour tells you it is a shop, and the icon
tells of what type).

**Comment by kocio-pl** [comment]
The legend in itself is very basic. Even the features included there like areas are hard to recognize, since they are presented only as a color bar with no important details (trees in the forest, dashing in allotments). Some other features like single parkings, trees, bollards, gates or proposed highways are just absent. The same for any font style.

As of now we also don't have any icon in the legend, so nothing new - no matter how many do we render, we already depend entirely on their recognizability.

**Comment by math1985** [comment]
Apart from the question whether we should add more icons, the question is what the best order would be. Either add the non-pixel-aligned now, and hope someone will align them later, or wait until somebody creates pixel-aligned icons and then add them.

The first has the advantage that we can use the icons now instead of having to wait. However, waiting for a pixel-aligned version means there is a stronger incentive to create a pixel-aligned version.

I'm inclined towards accepting the icons now, rather than waiting for an aligned version.

**Comment by nebulon42** [comment]
I have quite a strong opinion towards waiting for pixel-aligned versions. Introducing non-aligned SVG versions now will set a precedence towards a mess of aligned and non-aligned versions.

I'm currently using the transition towards SVG icons as a driver to promote pixel-aligned icons, which works quite well in raising the quality of iconography in osm-carto. I'm reluctant towards weakening this again.

Disclaimer: Please do not interpret this as me having some sort of problem with icons somebody else has designed.

**Comment by kocio-pl** [comment]
Sincerely, I'm tired with waiting even for common, non-controversial icons. Or for the clear reasoning why should we treat them as "not needed" at all. I just don't get the rules, while in my everyday (micro-)mapping activity I see tons of popular POI types left behind in the cold.

I appreciate your work no matter if I think particular icon redesign is better or worse than original - you really seem to care for recognizability and taste. And that's very good - we wouldn't move forward if we are afraid not to break something along the way, but at least we can try to avoid that.

I find your notion toward setting better standard for icons good and technically correct, but I think there are so many icons that IMO should be used, that even in you current (quite fast, I would say) rate that's gonna take months of constant work to have some of them. We could have about 17 ready, popular icons just for shops right now (according to taginfo it's about 100 with more than 500 uses and almost 200 with more than 100 uses, so let's say we may render about 10x more) - and I wouldn't like to have only shops, because we're not Google which cares only for commercial value. We still don't have the simple icon for such important place as clinic, for example, and it's already about 8 months since the issue was raised (https://github.com/gravitystorm/openstreetmap-carto/issues/763).

Given how much time and discussion can take to start rendering even some "easy" points like fountain (https://github.com/gravitystorm/openstreetmap-carto/issues/705 - also 8 months already and still ongoing), I don't want to make it even longer - quite the reverse.

Of course, when somebody comes with a nice, pixel-aligned SVG icon, that's great (like https://github.com/gravitystorm/openstreetmap-carto/issues/1404 / https://github.com/gravitystorm/openstreetmap-carto/pull/1451). But I don't consider current standard low by any measure - "pixel peeping" is a common term for overrating pixel-level accuracy while the overall image quality is good enough. I care the most for icons universal recognizability (as much as it's possible it should be read by anybody in the world), then for format (SVG>PNG) and only then for small technical details like aligning. We always can make them better in every aspect (even pixel-wise), but OSM would have never existed if started with too sophisticated set of standards.

**Comment by pnorman** [comment]
Converting to SVG and using non-pixel aligned offers no benefits for the map on the front page. I'd rather have aligned PNGs (i.e. ones without blurry edges) than misaligned SVGs.

**Comment by kocio-pl** [comment]
Converting is a bit different situation, when we already have the icon to make them better. But for me the key benefit (at least in straightforward, popular cases) is having clear symbols at all.

**Comment by math1985** [comment]
> Converting to SVG and using non-pixel aligned offers no benefits for the map on the front page. I'd rather have aligned PNGs (i.e. ones without blurry edges) than misaligned SVGs.

But that's not the question in this issue. The question is whether we want to use misaligned PNGs for new icons until we have aligned SVGs. @pnorman What do you think?

**Comment by pnorman** [comment]
No. In practice, misaligned SVGs are not well designed for low resolutions and have other problems.

**Comment by kocio-pl** [comment]
What problems do you mean?

**Comment by nebulon42** [comment]
I have icons for another 8 popular shop types ready. But before proposing PRs I'd like to have the green light from maintainers that this will be probably considered for merge as there seem to be 2 in favour, 2 against additional shop icons. There have been two additional shop icons lately and one being currently proposed. Shall I go ahead with this?

**Comment by kocio-pl** [comment]
I'd rather say 3-5 in favour: 3 for sure (me, @math1985, @matkoniecz), 2 most probably (@dieterdreist and you, I guess =} ). But still the simple voting count is of no use if @gravitystorm alone would oppose - that would be 3-5 vs infinity probably. ;-)

**Comment by math1985** [comment]
Indeed, this is not a democracy, and I'd prefer if decisions were based on convincing arguments rather than vote counts.

It's a shame @gravitystorm has not had time so far to join this discussion.

**Comment by pnorman** [comment]
> What problems do you mean?

Generally they're too detailed.

**Comment by kocio-pl** [comment]
> The legend in itself is very basic.

BTW: [somebody wants to work it out](https://lists.openstreetmap.org/pipermail/talk/2015-April/072545.html).

**Comment by kocio-pl** [comment]
User Wuzzy really pulled up and now there's a Wiki page for [standard tile layer](https://wiki.openstreetmap.org/wiki/Standard_tile_layer). It is not complete yet, but I guess we should use them as a simple documentation for what osm-carto does render and probably mention it in the Readme. More informations can be found in [this message](https://lists.openstreetmap.org/pipermail/talk/2015-April/072577.html) on a general Talk list.

**Comment by nebulon42** [comment]
@kocio-pl: Could you please update your list and cross out things that have been done already? This would make it easier to see what is still open.

**Comment by kocio-pl** [comment]
Sure - I guess I've checked all resolved (or mostly resolved, as shop=beverages is still below 1k uses and I don't think its that important) items.

**Comment by kocio-pl** [comment]
Do we plan to touch any issues I mentioned here other than just icons (namely *I. Low zoom level* and *II. Middle/high zoom level*) or they are too broad or we have any other problem with them?

**Comment by math1985** [comment]
As far as I'm concerned we could leave the issue open.

**Comment by HolgerJeromin** [comment]
the lines on sport pitches (#1126) could be added to the list.

**Comment by kocio-pl** [comment]
Thanks, I added it and some checkers too. I thought nobody else is interested, since there was no discussion on those "other" topics, but if we don't give up the idea, I'm happy to keep those things open and track the progress. 

Given that @cquest is following and open for code migration, we can discuss some details with him, but first we should decide what we want to have at all, what could be done first and what we want to be done  differently.

**Comment by math1985** [comment]
I'm interested (but lack spare time to actively work on it at the moment).

**Comment by pnorman** [comment]
Thinking about it, with the french style using a JSON MML and us using YAML, moving code over is basically impossible, as we'd need to rewrite any layers

**Comment by kocio-pl** [comment]
Code porting can be a problem then, but we can still use some of their ideas if we like them or just take the inspiration. I was surprised nobody commented their rendering for a start.

**Comment by kocio-pl** [comment]
@cquest 
> For the low level zooms, I'm planning to rework on it, to speed up rendering.

This is interesting for me, as I'd like to take care of low levels here. What is the current state of this idea?

**Comment by cquest** [comment]
I've paused on working on the french style for the moment.
I'm currently more focused on switching to vector tiles and experimenting in that area with some light vector tile server to see the impact on rendering.

**Comment by kocio-pl** [comment]
This is also interesting thing for me. :smile: If you will have some links to try or even half-baked conclusions, I would be happy to hear about it too.

**Comment by kocio-pl** [comment]
Some more interesting features may be found [in a special guide](http://openstreetmap.fr/blogs/cquest/visite-guidee).

**Comment by kocio-pl** [comment]
There are some new changes in French style, in case anybody is interested:

https://cquest.hackpad.com/Rendu-OpenStreetMap-FR-v2017-PYR3VV1ZrSe

**Comment by kocio-pl** [comment]
I feel that porting is not a way to go - I learned a lot about this style and I don't need separate ticket for finding interesting solutions, so I'll close it now.
