### ISSUE TITLE
A list of possibly deprecated, but rendered tags:

### ISSUE THREAD

**Issue by tyrasd** [gravitystorm/openstreetmap-carto#204]
After reading the [guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md#purposes) I've hacked together a [script](https://github.com/tyrasd/openstreetmap-carto-typos) that searches for typos and deprecated tags in the openstreetmap-carto stylesheet. It does this by searching for key-value tag selectors in the cartocss stylesheets and cross-checking those with the [taginfo databases](http://taginfo.openstreetmap.org/download). Tags that can't be found on neither the tables for popular tags nor the table for wiki-documented tags are filtered out.

In the end I've come up with the following list of tags that are rendered in openstreetmap-carto, but are undocumented and not used widely:

### aerialways.mss
- [x]	 ~~[aerialway=j-bar](http://taginfo.openstreetmap.org/tags/aerialway=j-bar)~~
- [x]	 ~~[aerialway=rope_tow](http://taginfo.openstreetmap.org/tags/aerialway=rope_tow)~~

### amenity-points.mss
- [X]	 [amenity=bus_stop](http://taginfo.openstreetmap.org/tags/amenity=bus_stop) #667
- [x]	 [amenity=chalet](http://taginfo.openstreetmap.org/tags/amenity=chalet) ~~#226~~ #238
- [x]	 [waterway=lock](http://taginfo.openstreetmap.org/tags/waterway=lock)
- [x]	 [amenity=picnic_site](http://taginfo.openstreetmap.org/tags/amenity=picnic_site) #208
- [x]	 [tourism=bed_and_breakfast](http://taginfo.openstreetmap.org/tags/tourism=bed_and_breakfast) #695, #1059
- [x]	 [landuse=grave_yard](http://taginfo.openstreetmap.org/tags/landuse=grave_yard) #793

### buildings.mss
- [x]	 [building=station](http://taginfo.openstreetmap.org/tags/building=station)

### landcover.mss
- [x]	 [natural=field](http://taginfo.openstreetmap.org/tags/natural=field) #617
- [x]	 [landuse=grave_yard](http://taginfo.openstreetmap.org/tags/landuse=grave_yard) #793

### placenames.mss
- [x]	 [place=metropolis](http://taginfo.openstreetmap.org/tags/place=metropolis) #224
- [x]	 [place=large_town](http://taginfo.openstreetmap.org/tags/place=large_town) #225
- [x]	 [place=small_town](http://taginfo.openstreetmap.org/tags/place=small_town) #225 
- [x]	 [place=large_village](http://taginfo.openstreetmap.org/tags/place=large_village) #223

### roads.mss
- [x]	 ~~[highway=runway](http://taginfo.openstreetmap.org/tags/highway=runway) #206~~
- [x]	 ~~[highway=taxiway](http://taginfo.openstreetmap.org/tags/highway=taxiway) #206~~

### water.mss
- [x]	 [waterway=mill_pond](http://taginfo.openstreetmap.org/tags/waterway=mill_pond)
- [x]	 [landuse=water](http://taginfo.openstreetmap.org/tags/landuse=water)

**Comment by mkoniecz** [comment]
building=station is no longer considered special.

**Comment by pnorman** [comment]
all resolved.
