### ISSUE TITLE
Code needed to render prepared icons [meta ticket]

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3105]
We have lot more icons for requested features lately, mainly due to a great designing work of @Tomasz-W (thanks!). The problem is that they will be not shown until somebody do the coding. Some of them require  just "copycat" skills and running a testing environment ([in Docker](https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md) probably). Some are more complex, but one still doesn't have to be a programmer to make it (especially after reading [some background intro](https://wiki.openstreetmap.org/wiki/Standard_tile_layer#Technical_details), [tutorials](https://ircama.github.io/osm-carto-tutorials/) or a [real life example](https://www.openstreetmap.org/user/SomeoneElse/diary/43041)) and I'm willing to help.

Just please remember that after PR (pull request) is ready, you still need to interact with people as it's very common that people have different wishes, requests or questions, even when the case seems like very obvious (see [this example](https://github.com/gravitystorm/openstreetmap-carto/pull/3085)).

Here is the (open!) list of things which I feel are ready to prepare a PR and test rendering a bit:

Easy ones (one feature per ticket, no subtags):
- [x] Add rendering for shop=dairy #3087 
- [x] Add rendering for amenity=shower #3067 
- [x] Add rendering for leisure=sauna #3062 
- [x] Rendering of amenity=bbq #2996
- [ ] <s>Render amenity=studio #2518</s>
- [ ] Peaks and saddles are hardly visible #2848 
- [ ] Names for wind turbines #2734 
- [x] Add icon for shop=music #2929 
- [ ] Add icon for shop=ticket #3115  
- [x] render label for historic=city_gate #152 

Complex ones (multiple objects with subtags):
- [x] Guidepost and Map Icon #1978 #3246
- [ ] Add rendering for barrier points #846 
- [ ] Distinguish different memorial types #3088

**Comment by Tomasz-W** [comment]
A few days ago I though about a tag like "pr needed", which could be added to mark issues where we all agree that icon/ icons are ok, and just wait for someone to write the code. I think this would be easier to manage than a next one issue with task list.
Anyway - thank you for sorting things out here :)

**Comment by kocio-pl** [comment]
I hope more personal touch and a few words of explanation might work better than just a tag.

@althio @RobJN Would you like to pick anything from that list?

**Comment by Tomasz-W** [comment]
Another ones:

single icons:
* advertising=column https://github.com/gravitystorm/openstreetmap-carto/issues/3002
* amenity=bicycle_repair_station https://github.com/gravitystorm/openstreetmap-carto/issues/3069
* amenity=clock https://github.com/gravitystorm/openstreetmap-carto/issues/3070
* shop=medical_supply https://github.com/gravitystorm/openstreetmap-carto/issues/2660
* waterway=waterfall https://github.com/gravitystorm/openstreetmap-carto/issues/336
* chess tables https://github.com/gravitystorm/openstreetmap-carto/issues/3039

sets of icons:
* craft=* https://github.com/gravitystorm/openstreetmap-carto/issues/1697
* water points and taps https://github.com/gravitystorm/openstreetmap-carto/issues/3011
* water wells https://github.com/gravitystorm/openstreetmap-carto/issues/1224

**Comment by Tomasz-W** [comment]
New ones:
* shop=charity https://github.com/gravitystorm/openstreetmap-carto/issues/1869
* office=lawyer https://github.com/gravitystorm/openstreetmap-carto/issues/1922
* vending=parking_tickets https://github.com/gravitystorm/openstreetmap-carto/issues/2541

**Comment by pnorman** [comment]
If we're adding this many icons, what are we going too be removing?

**Comment by kocio-pl** [comment]
1. The things we don't want to render.
2. Code duplication.
3. Parts of documentation that are no longer true.

I don't share the assumption that adding some things means removing some others.

**Comment by Tomasz-W** [comment]
@kocio-pl Can you copy elements from https://github.com/gravitystorm/openstreetmap-carto/issues/3105#issuecomment-371597884 and paste them to the task list in first comment?

**Comment by kocio-pl** [comment]
I wanted to show the list of things that are more or less ready, but not all the discussions are resolved in my opinion and I prefer to do the easier ones first.

**Comment by Tomasz-W** [comment]
Ok, we can treat it as 'phase 2' to focus on :)

**Comment by kocio-pl** [comment]
Sure, I can even add them one by one when I think the solution is established enough. It's just my idea for a "social helper tool" to help start with coding, but one can go on with any issue ticket or even without the ticket if she feels like.

BTW: have you thought about preparing PRs too?

**Comment by james2432** [comment]
If Tomasz-W wants to keep belting out icons, I don't mind making the pull requests. I can't stand inkscape with it's ever changing image canvas size

**Comment by Tomasz-W** [comment]
`BTW: have you thought about preparing PRs too?`

I thought, but it get out of me fast ;) I'm more technical than an average person, but not as much as writing the code requires,. It's just not interesting me. I'm self-made graphic designer (you can see my projects here: https://tomoziomo.deviantart.com/gallery/), so making icons fits my hobby very well.

`If Tomasz-W wants to keep belting out icons, I don't mind making the pull requests.`

Great! Like factory line.

**Comment by kocio-pl** [comment]
That's great for me to see a teamwork spirit in this project.

I like to know different aspects, so I couldn't make big code changes, but I can do one man show (icon designing, simple coding, review and testing, managing the release and community, communication with upstreams etc.). However that's what I like to achieve my goals and if we have enough people in the active team it doesn't really matter what part anyone is interested in. It's just good if there's more than one person able to deal with something.

**Comment by kocio-pl** [comment]
Any other people willing to try some coding? We need you, even if you're not a coder and want to learn basics, since there are many of the tickets open and only few people active.

**Comment by doktorpixel14** [comment]
I would help, but I don't have that much coding knowledge. So it would be good if there was a tutorial or if someone would give me instructions.

**Comment by kocio-pl** [comment]
Great! I'm not a coder, but most of the time experience, testing and looking at the code for similar objects is enough. 

I would start with installing testing environment:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

Let me know how far did you go with it. Also please read a bit about this style in general:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer

**Comment by doktorpixel14** [comment]
I have some problems with installing the virtual environment. I now have a virtual Ubuntu running with Docker installed. But when I try to import the osm-carto repository I get the following error:
![docker error](https://user-images.githubusercontent.com/23462396/38032283-8b0ed0a4-329d-11e8-8017-3f8fbc344171.png)
I also managed to start kosmtik somehow. Is that correct?

**Comment by james2432** [comment]
you need to start the docker service:
sudo systemctl start docker

or 

sudo systemctl enable docker   (to not have to start it every reboot)
sudo systemctl start docker

**Comment by doktorpixel14** [comment]
Doesn't help, unfortunately

**Comment by james2432** [comment]
docker is retarded as it binds to a port and has to run as root.

Are you part of the docker group?

sudo gpasswd -a $USER docker

**Comment by kocio-pl** [comment]
If you don't have the access to a Docker daemon, it most probably means that only root has these rights by default and you should add current user to a docker group:

https://docs.docker.com/install/linux/linux-postinstall/

There are no really secure solutions when talking about Docker, but if it's your personal machine, you can do it instead of running sudo all the time.

As of Kosmtik, it doesn't look good, please give us more informations what do you do.

**Comment by james2432** [comment]
you also would need to run :

newgrp docker

or log out and log back in

**Comment by james2432** [comment]
or less secure easier way prepend sudo to all docker-compose commands:

sudo docker-compose .....

**Comment by doktorpixel14** [comment]
@james2432 Thank you, the error disappeared after I added my account to the docker group!

**Comment by doktorpixel14** [comment]
But another problem occurred: In the guide it says that PostgreSQL would start up after typing 'docker-compose up import'. That didn't happen. Instead kosmtik started again with this being the last lines:
![docker error](https://user-images.githubusercontent.com/23462396/38038561-8249b5ca-32ab-11e8-995e-04ecb9dd30d2.png)

**Comment by kocio-pl** [comment]
Which steps did you do before from Quick start section? Do you have some data file (like PBF) downloaded in the proper directory?

**Comment by kocio-pl** [comment]
Wht is the output of this command in the osm-carto directory:

```bash
ls *.pbf
```

**Comment by doktorpixel14** [comment]
`data.osm.pbf`

**Comment by kocio-pl** [comment]
1. What file did you downloaded - could you check if the md5sum is the same as on the site?:

```bash
ls -la data.osm.pbf
md5sum data.osm.pbf
```

2. Is it real file or just a symbolic link maybe? Docker has no power outside the mounted volume.

**Comment by doktorpixel14** [comment]
Yes, the md5sum is the same (I downloaded 'Italy - Sud' from Geofabrik. (Didn't find a way to download smaller areas))

And yes, it's a real file of 200+ MB.

**Comment by doktorpixel14** [comment]
Ok, I'm running the kosmtik application now, but it doesn't render anything ... It's not that easy as I thought

**Comment by kocio-pl** [comment]
> EDIT: Seems to work now ;-)

Do you know what was the problem?

> Ok, I'm running the kosmtik application now, but it doesn't render anything

Do you look in a proper place? Could you post a screenshot to show what do yo exactly mean by "nothing"?

**Comment by doktorpixel14** [comment]
> Do you know what was the problem?
Well, sometimes a simple restart can be the solution ...

And I think this was also the solution for kosmtik not rendering anything. When I started my virtual machine this morning it rendered without any issue.

So is there any guide about how to test new things and how to add them to the code?

**Comment by kocio-pl** [comment]
There is a detailed example, which I think might be very useful:

https://www.openstreetmap.org/user/SomeoneElse/diary/43041

I started just by looking on the code for similar objects, for example lately merged shop and amenity (very popular types):

- https://github.com/gravitystorm/openstreetmap-carto/pull/3127/files
- https://github.com/gravitystorm/openstreetmap-carto/pull/3134/files

Let me know how does it go or if you need something more.

**Comment by doktorpixel14** [comment]
Thank you, I did my first tests now with [leisure=beach_resort](https://github.com/gravitystorm/openstreetmap-carto/issues/2440).

**Comment by Tomasz-W** [comment]
@kocio-pl As I'm continuously updating my https://github.com/gravitystorm/openstreetmap-carto/issues/3105#issuecomment-371597884 and try to coordinate work of coders, can I open new ticket for this issue, where my list will be the first post? I think it would be better so see actual progres bar of the task list and not to scrolling the page for certain post.

**Comment by kocio-pl** [comment]
OK. When you will open your ticket, I will close this one.

**Comment by Tomasz-W** [comment]
The new ticket with reguraly updated task list in the first post is https://github.com/gravitystorm/openstreetmap-carto/issues/3298.

Since opening this one, we have added 8 new icons. Thanks for all the contributors! :)

**Comment by kocio-pl** [comment]
Also thank you all. Let's move to the new ticket now.
