### ISSUE TITLE
Labeling based on size (meta issue)

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3284]
There is an issue with labeling based on size for some POI areas, but the discussion about this problem and how to resolve it broken into few pieces and get messed. I propose to close some dead tickets (which actually are the same multiplicated ticket) and move whole discussion into one meta issue.

The most substantive parts was in: 
* https://github.com/gravitystorm/openstreetmap-carto/pull/2361#issuecomment-249083347
* https://github.com/gravitystorm/openstreetmap-carto/issues/2704#issuecomment-328608781

Involved tags:
- [ ] amenity=school (https://github.com/gravitystorm/openstreetmap-carto/issues/120)
- [ ] amenity=hospital (https://github.com/gravitystorm/openstreetmap-carto/issues/1019)
- [ ] amenity=prison (https://github.com/gravitystorm/openstreetmap-carto/issues/1022)
- [ ] tourism=camp_site (https://github.com/gravitystorm/openstreetmap-carto/issues/1020)
- [ ] amenity=place_of_worship (https://github.com/gravitystorm/openstreetmap-carto/issues/1052)
- [ ] historic=archaeological_site (https://github.com/gravitystorm/openstreetmap-carto/issues/2073)
- [ ] amenity=university, college (https://github.com/gravitystorm/openstreetmap-carto/pull/2361)
- [ ] amenity=childcare, kindergarden (https://github.com/gravitystorm/openstreetmap-carto/issues/2657)
- [ ] tourism=museum (https://github.com/gravitystorm/openstreetmap-carto/issues/2704)

Related tickets:
* Render labels of large POI larger https://github.com/gravitystorm/openstreetmap-carto/issues/1055
* Render icon and icon+text for large POIs on lower zoom levels https://github.com/gravitystorm/openstreetmap-carto/issues/1057
* Outline coordination https://github.com/gravitystorm/openstreetmap-carto/issues/3045

**Comment by polarbearing** [comment]
IIRC what blocks scalable labelling for some objects above is the **presence of icons**.
We have not yet agreed how to handle this, i.e. the icon would need to scale with the text label.
One idea was to have a set of label sizes, e.g. three or so, with according text font sizes.

@Tomasz-W - Thanks for your summary in this ticket!
