### ISSUE TITLE
Coordinate shades of non-physical green areas (meta-ticket)

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3517]
As we have a lot of different green shades on map, and some of them are discussed or considered as unnecessary, I'm opening meta-ticket to coordinate whole topic.

Ticket assumptions:
* ~~make park colour more greenish instead of blueish~~
* ~~make park colour more prominent~~
* ~~distinguish @_park_ and @_leisure_ colours more from each other~~
* eliminate some unnecessary green shades from map

Propositions of this ticket:
- [ ] test outlines for parks (https://github.com/gravitystorm/openstreetmap-carto/issues/3264)
- [ ] change `leisure=golf_course` and `leisure=miniature_golf` area fill to @_leisure_ (they are both just a kind of sports centres, so I don't see a reason for using special color here) (https://github.com/gravitystorm/openstreetmap-carto/issues/2069)
- [ ] change `leisure=common` area fill to @_leisure_ (rendering it the same as grass leads to bad tagging like here: https://www.openstreetmap.org/way/270339855)
- [ ]  drop `tourism=campsite` and `tourism=caravan_site` filling (current colour is too close to grass and might be confused with some landcover rendering; these sites are usually a group of tents and tourism-related nodes throwed on a bigger area of grass; we use fills rather for areas with some clear edges, in this case outline is usually random, so area filling is confusing) (https://github.com/gravitystorm/openstreetmap-carto/issues/1485)
- [ ] drop fill for `tourism=picnic_site` (these sites are usually a group of tourism-related nodes throwed on a bigger area of grass; we use fills rather for areas with some clear edges, in this case outline is usually random, so area filling is confusing)
- [ ] move `leisure=sport_centre` and `leisure=stadium` to @_leisure_ key (just code simplifying)
- [ ] test moving @_golf_course_ colour for pitches

**Comment by ghost07tula** [comment]
Isn't new park color too aggressive?

**Comment by Adamant36** [comment]
Its a tad over saturated. It might look different in rendering tests. We are kind of running out of options when it comes to green colors though.

**Comment by jeisenbe** [comment]
I think it is too bright (saturated).
Perhaps we could try the current golf course or campground color, if we are
not using those anymore.

**Comment by Adamant36** [comment]
![download](https://user-images.githubusercontent.com/30259065/48718633-9d533100-ebd0-11e8-984e-6da77a22549d.png)
To over saturated. I like whatever color it is zoomed out though. 
![download 1](https://user-images.githubusercontent.com/30259065/48718662-ad6b1080-ebd0-11e8-87a6-c4a6867dba76.png)

**Comment by Tomasz-W** [comment]
It's hard to find a shade which won't mix with e.g. grass areas mapped on a park area, but I can understand that proposed new park colour might be too hard for some people. I'll look for a better (less bright) shade later :)

**Comment by Adamant36** [comment]
That's fine. What about using the darker color that it is when its zoomed out? I don't know what the RGB for it is, but id like to test it out. Maybe you would like to find out since that's not my department?

**Comment by kocio-pl** [comment]
There is also one important physical green to test, I mean forest/wood. It looks better for me in the @imagico fork for low zoom if tested without colors fading. I was not aware that it has been changed in the fork and that is basic green for low zooms, so I would start with investigating it a bit. See this comparison: https://github.com/gravitystorm/openstreetmap-carto/issues/3513#issuecomment-439042799.

I consider forest/wood and grass greens as a map base and all the other greens being secondary, because they are less popular.

**Comment by Tomasz-W** [comment]
The same places with `#aaf2b6` for parks and `#d9ffd9` for leisure areas:

![park1](https://user-images.githubusercontent.com/25656654/48732422-eee6d480-ec3f-11e8-855f-b4c8e0530917.jpg)
![park2](https://user-images.githubusercontent.com/25656654/48732425-eee6d480-ec3f-11e8-860e-b1b45c1e9104.jpg)
![park3](https://user-images.githubusercontent.com/25656654/48732426-eee6d480-ec3f-11e8-92d2-f10075b215f5.jpg)
![park4](https://user-images.githubusercontent.com/25656654/48732427-eee6d480-ec3f-11e8-9597-e9d625b513e0.jpg)
![park5](https://user-images.githubusercontent.com/25656654/48732428-ef7f6b00-ec3f-11e8-83f1-077933bf77d8.jpg)
![park6](https://user-images.githubusercontent.com/25656654/48732429-ef7f6b00-ec3f-11e8-9b73-3d299105fa8d.jpg)
![park7](https://user-images.githubusercontent.com/25656654/48732431-ef7f6b00-ec3f-11e8-8697-ab12aedec9be.jpg)
![park8](https://user-images.githubusercontent.com/25656654/48732432-f0180180-ec3f-11e8-91bd-01a602c876fa.jpg)
![park9](https://user-images.githubusercontent.com/25656654/48732433-f0180180-ec3f-11e8-9442-57f26e9b798f.jpg)
![park10](https://user-images.githubusercontent.com/25656654/48732434-f0180180-ec3f-11e8-9985-f649cc92e13b.jpg)
![park11](https://user-images.githubusercontent.com/25656654/48732435-f0180180-ec3f-11e8-802f-54316330b865.jpg)
![park12](https://user-images.githubusercontent.com/25656654/48732436-f0b09800-ec3f-11e8-8a64-b673ab95cac0.jpg)

I'm very satysfied with these ones, I think that they are both not too hard and match good with each other as park and leisure areas are quite common landcover combination.

**Comment by jeisenbe** [comment]
The delta from aaf2b6 to d9ffd9 is 18.2, which seems unnecessarily large, because leisure areas share many similarities with parks. I would stick with lighten 5% instead of 20%, for leisure.

I also believe aaf2b6 is too saturated. Lch is 90, 41, 147; compare this to Lch 84, 36, 138 for orchards (aedea3) or Lch 86, 29, 143 for current golf (b5e3b5); the second number shows the saturation level.

This may be why aaf2b6 looks strange next to grass and forest areas. 

I suggest using the current golf color for parks, because it is already designed to look good with forest, grass, water and sand areas, found on golf courses. Lightened 5% it will work well as the leisure color (though the outlines and text will need adjusting):

**Golf course and caravan campsite, Newcastle**
current:
![caravan-golf-county-down-before](https://user-images.githubusercontent.com/42757252/48754035-a1b44280-ecd3-11e8-8657-2c4856dc7544.png)
After changing park to b5e3b5, with golf course and caravan / campsite = leisure (park lighten 5%)
![caravan-golf-countydown-after](https://user-images.githubusercontent.com/42757252/48754078-c6a8b580-ecd3-11e8-8459-1aad5a2d4c4e.png)

**Victoria Park, Belfast**
- Includes forest, leisure area, pitches and orchard
Current:
![victoria-before](https://user-images.githubusercontent.com/42757252/48754549-61ee5a80-ecd5-11e8-9edc-97637900acc8.png)
Park changed to b5e3b5, pitch changed to b8dabd
![victoria-park-after](https://user-images.githubusercontent.com/42757252/48754568-7b8fa200-ecd5-11e8-9ac0-0429b1bc704d.png)

**Kilbroney Park, in Rostrevor, Northern Ireland**
- There are two caravan campsites between the park and the forest
Current:
![kilbroney-before](https://user-images.githubusercontent.com/42757252/48754578-83e7dd00-ecd5-11e8-8307-183320817a66.png)
After (Park b5e3b5, pitch b8dabd)
![kilbroney-after](https://user-images.githubusercontent.com/42757252/48754582-88ac9100-ecd5-11e8-81e2-ddaf21b283b3.png)

**Comment by Adamant36** [comment]
I wouldn't have a problem with that. Except parks don't have an icon. Whereas golf courses and campgrounds do. So I think there's a need to have parks colored differently. Although, they were the same color as campgrounds already anyway. So I guess its not that much of a difference. Then we could make pitches an X% darken of it. 

Anyone know if golf courses are considered pitches (probably the green only would be my guess)?

There's also other leisure green things like dog parks that then need to be considered because they have the same color (?).

**Comment by jeisenbe** [comment]
My proposal was to change the pen color, while also changing golf courses
to leisure color.
The color for parks is currently different from that used for campsites and
caravan sites (“RV parks” in ‘Merican), and also different from golf
courses, which are different from leisure (eg sports centers), so there are
5 non-vegetation green area features:

1) Parks and recreation grounds
2) Pitches
3) Leisure (eg sports centers)
4) Campsite / caravan site
5) Golf

National parks and reserves have a green border, with a light-green fill at
some zoom levels.

Also farmland, orchards/vineyards, grass, gardens, scrub and woods are
shades of green (heath is mainly brown)

Tomasz-W has proposed reducing it to 3 non-vegetation greens

1) Parks and recreation grounds
2) Pitches
3) Leisure (eg sports centers), including Campsite / caravan site, and Golf
/ mini golf.

I agree that this would be helpful.

Alternately, campsites and caravan sites could get a different non-green
color, because they are accommodations and tourism related.

**Comment by Tomasz-W** [comment]
@jeisenbe As @Adamant36 already said, please don't mix so many things in one place, because it makes any single one hard to response. I really appreciate your enthusiasm and work, but by proposing changes this way you make big mess and reading it gives a real 'mindf*ck'.

My remarks:
* Difference between proposed park and leisure colours: I don't care about some calculated lch difference values, because at the end of a day nobody is sitting in front of a map with calculatoor looking for a round numbers, our goal is to make an intuitive and  good-looking map.
* Notice that park areas should be a little bit more saturated than rest of green areas. We use pastel colours for physical landcovers and more bright ones for cultural-like areas (and parks are partly a cultural-like)
* Golf colour totally doesn't work for parks for me, I think it should be keeped light, and golf colour is too dark

I would like to see some  `#aaf2b6 `for parks and `#d9ffd9 `for leisure areas test renderings in different regions of the world (less mapped and more mapped).

**Comment by Adamant36** [comment]
I totally agree with @Tomasz-W about the uselessness of lch values in this context. In the couple of years I've been following along its never been a part of any decision about how to color things that I can remember. If it ever did matter, it wasn't for anything similar to how things like parks should be rendered. Also, id guess most people, besides the most hardcore contributors, who browse around and comment here on things don't even know what it does. Even if they did though. Its still completely worthless as a variable and should probably just be left alone.

**Comment by jeisenbe** [comment]
@Adamant36, the Lch values of the primary landcovers are listed in the code at landcover.mss, suggesting that these were considered important by previous contributors and maintainers. Eg:
```
@farmland: #eef0d5;         // Lch(94,14,112)
@farmland-line: #c7c9ae;    // Lch(80,14,112)
```
```
@forest: #add19e;       // Lch(80,30,135)
@forest-text: #46673b;  // Lch(40,30,135)
```
```
@residential: #e0dfdf;      // Lch(89,0,0)
@residential-line: #b9b9b9; // Lch(75,0,0)
@retail: #ffd6d1;           // Lch(89,16,30)
@retail-line: #d99c95;      // Lch(70,25,30)
```
etc.

The "L" represents lightness, with 0 black and 100 white; "c" represents chroma, which is similar to the color saturation; 0 is gray, 100 if full-color. And "h" stands for hue, or the specific color in the rainbow. 

I find it much more helpful to look at the Lch values than to just look at a hex code like "d1e0b4". 
The important thing is that we need the lightness and hue to be different enough so that each area can be distinguished, but the color saturation cannot be too high or low.

**Comment by jeisenbe** [comment]
Looking at the current colors, _c is never above 30,_ and the built-up areas like retail, commercial, and industrial are actually only have c values of 16, 8.5 and 9; that is, they are not very saturated colors. 

This is an objective way to explain my subjective feeling that aaf2b6 is too strong of a color for parks: Lightness is 90 (fine), chroma is 41 (too high), hue is 147 (slightly blueish green). 

I also feel d9ffd9 is too light for leisure areas:  Lch is 97, 24, 144; so lightness is 97 - that's really high, even lighter than farmland (94) and it's right at the limit of what my monitor can display.

The current park color is c8facc , or Lch(94,30,135); it's much less saturated and a little more yellow (less blue) than the suggested color aaf2b6.

I agree with you the golf color wouldn't work, because it doesn't play well with the current water color in the test renderings. 

So I would suggest reducing the park color lightness to 90, just like @Tomasz-W planned, but keeping the c at 30, or even reducing it to be more similar to the developed landuse colors.

This would mean something like ceebc1 (90,24,135) or c3eebd (90,30,140) or bdefc1 (90,30,145) for parks, and then lightening this 5% to 10% for leisure.

**Comment by Adamant36** [comment]
@jeisenbe, thanks for the information. I wasn't aware that's what it did. It sounds sorta useful, but still to over complicated and unnecessary. Since we have always gone by hex values, which all those things can be modified with also, and it has gone fine. Its much easier to just say "test this hex value," which is recognized by Google etc then to try and decipher lch values along with the hex value. Plus, its really just extra information for the sake of extra information. Since like I said hex values work perfectly fine on their own. There's a lot of cool little nobs and buttons that we could potentially tweak just for the sake of it, that doesn't mean we should though. 

Also, a lot of the reasons I'm involved in this project is to make things easier for mappers and other contributors in general. So, I think its worth leaving out anything to "techie" if we can so we don't alienate random on lookers from commenting or creating new issues. So, I'm usually always going to come from the paradigm of simpler and more standardized is better.

**Comment by jeisenbe** [comment]
What problem are we trying to solve by changing the park color? I don't see any open issue about this. 

@Tomasz-W wrote:
> Make park colour more greenish instead of blueish
> make park colour more prominent
> distinguish @park and @leisure colours more from each other"

But what are the particular benefits of these changes? Is it difficult to see water areas in or next to parks because of the blue tone?
Why do parks need to be more prominent than currently?
Why should the leisure color be more distinct from park color?

I see that the suggested "new" leisure color is very similar to the current leisure color, so park is what is changing, rather than leisure. 

There was a previous issue about the color of pitches and tracks: #1190 and a PR in #2363, but there have still been comments in more recent issues about the color being too strong.

**Comment by kocio-pl** [comment]
I also don't see any reason t change park color. I can recognize it perfectly and it is quite different than leisure green too.

**Comment by Tomasz-W** [comment]
It's a design purpose, I belive it would make map looking better and more "up-to-date" with its colour palette, because current park shade is too blueish in opinion of some map users and it should be more greenish.

**Comment by dieterdreist** [comment]
sent from a phone

> On 27. Nov 2018, at 14:05, Tomasz Wójcik <notifications@github.com> wrote:
> 
> It's a design purpose, I belive it would make map looking better and more "up-to-date" with its colour palette, because current park shade is too blueish in opinion of some map users and it should be more greenish.


historically, this style differentiated between natural green areas, and cultural green areas (the latter e.g. being sport related, playgrounds at the extreme, park was tending towards cultural areas, but in between).
Is this layer of meaning still in the project’s concept, or has it been replaced with something else?

How does the proposed change integrate in the overall concept of color coding?

**Comment by kocio-pl** [comment]
> current park shade is too blueish in opinion of some map users and it should be more greenish

I'm not aware of such ideas. Given how many greens we need, I don't believe we have too much choice - it's still green for sure, and some will need to be more yellowish or blueish (in the green range) to be distinctive. And certainly I don't think it's outdated or something to be updated. There's nothing wrong with this color for me and I guess we have enough hard problems related to greens to touch another one.

**Comment by Tomasz-W** [comment]
Due to discussion above, I've updated tasks in first post.

**Comment by jeisenbe** [comment]
I'm going to close this meta-ticket. Please open a new, more specific issue if there are specific ideas that have not yet been addressed
