### ISSUE TITLE
Good first issues [meta-ticket]

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3617]
### Regularly updated task list:
**add single icons:**
- [ ] historic=ruins https://github.com/gravitystorm/openstreetmap-carto/issues/331
- [ ] leisure=horse_riding https://github.com/gravitystorm/openstreetmap-carto/issues/2344
- [ ] amenity=studio https://github.com/gravitystorm/openstreetmap-carto/issues/2518
- [ ] _leisure-green_ generic dot (sports_centre https://github.com/gravitystorm/openstreetmap-carto/issues/2930, escape_game https://github.com/gravitystorm/openstreetmap-carto/issues/3368, dance https://github.com/gravitystorm/openstreetmap-carto/issues/3495)
- [ ] bench with backrest https://github.com/gravitystorm/openstreetmap-carto/issues/3187
- [ ] natural=rock https://github.com/gravitystorm/openstreetmap-carto/issues/2616
- [ ] man_made=petroleum_well https://github.com/gravitystorm/openstreetmap-carto/issues/3494
- [ ] memorial benches https://github.com/gravitystorm/openstreetmap-carto/issues/3527
- [ ] ferris wheels https://github.com/gravitystorm/openstreetmap-carto/issues/3550
- [ ] amenity=clock ~~https://github.com/gravitystorm/openstreetmap-carto/issues/3070~~ -> ~~PR https://github.com/gravitystorm/openstreetmap-carto/pull/3135~~ -> https://github.com/gravitystorm/openstreetmap-carto/issues/3577
- [ ] historic=milestone https://github.com/gravitystorm/openstreetmap-carto/issues/3605

**add sets of icons:**
- [x] barriers https://github.com/gravitystorm/openstreetmap-carto/issues/846 -> done! https://github.com/gravitystorm/openstreetmap-carto/pull/3450 https://github.com/gravitystorm/openstreetmap-carto/pull/3602
- [x] vending machines https://github.com/gravitystorm/openstreetmap-carto/issues/2541#issuecomment-372374090 -> done! https://github.com/gravitystorm/openstreetmap-carto/pull/3601 _(note: we wait for packstations proper tagging clarification to add also them, see https://github.com/gravitystorm/openstreetmap-carto/issues/1561#issuecomment-373943968)_
.
- [ ] sport=* https://github.com/gravitystorm/openstreetmap-carto/issues/844 https://github.com/gravitystorm/openstreetmap-carto/issues/2930 _-> PR https://github.com/gravitystorm/openstreetmap-carto/pull/3578_ (icons for pitches)
   - [ ] equestrian https://github.com/gravitystorm/openstreetmap-carto/issues/2344
   - [ ] 9pin/10pin https://github.com/gravitystorm/openstreetmap-carto/issues/3398
- [ ] water wells https://github.com/gravitystorm/openstreetmap-carto/issues/1224
- [ ] craft=* https://github.com/gravitystorm/openstreetmap-carto/issues/1697 -> ~~PR https://github.com/gravitystorm/openstreetmap-carto/pull/3126~~
- [ ] water points and taps https://github.com/gravitystorm/openstreetmap-carto/issues/3011

**Comment by Tomasz-W** [comment]
@kocio-pl Can you move this ticket to first place in pinned ones as it was there before?

**Comment by kocio-pl** [comment]
Done (by stupid unpin/pin in the proper order...).

**Comment by Tomasz-W** [comment]
@Adamant36 When I will have more time, I plan to gather small bugs like e.g. tags rendering priority there.

**Comment by boothym** [comment]
Not sure if you're looking for more issues, but #3271  (rendering ref instead of name) and #2074 (choosing one feature to move to a different zoom level) seem fairly straightforward to fix.

**Comment by matthijsmelissen** [comment]
This ticket is duplicate with the [https://github.com/gravitystorm/openstreetmap-carto/labels/good%20first%20issue](good first issue) label which we had already when this ticket was opened. I would propose closing this topic. If there are good tickets to add the label to, please do so in their respective topics.

I also don't think a list of about fifty good first issues is useful. About 5-10 should be enough, I believe.

I'd propose closing this topic as duplicate with the tag.

**Comment by matkoniecz** [comment]
I also think that it may be closed, if something is easy to do and has no label - then it can be added.

**Comment by jeisenbe** [comment]
It might be helpful to have a link to the firsts issues labels in
contributing.md

Also, can these labels be added by all contributors or only by maintainers?

**Comment by matkoniecz** [comment]
maintainers, and unfortunately it is not doable by pull requests as it is not a part of repository bit of a Github database. But commenting proposing to add label or creating an issue requesting it should work well.

**Comment by matthijsmelissen** [comment]
> It might be helpful to have a link to the firsts issues labels in
contributing.md

It is, in fact:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#easy-pickings

**Comment by HolgerJeromin** [comment]
We should unpin this issue.
