### ISSUE TITLE
Important todos

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#4901]
With over 500 open issues it is fairly difficult for contributors to identify issues with high importance to work on.  We have the [good first issue](https://github.com/gravitystorm/openstreetmap-carto/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) label to indicate low hanging fruits suitable also for less experienced developers.  But we don't have any good starting point to find the most important tasks.

This is not meant as a list for newcomers, it is mostly about strategic issues that need substantial work but that are significant to make progress on other things and to really move the style forward.

- [ ] _the move to the flex backend,_ #4431, mostly needs discussion and consensus building on if or not to have the separate transport tables, a few smaller issues with the admin boundary rendering need addressing but fixes for those have already been suggested.
- [ ] _consistent poi symbol and label prioritization_, #3880, requires working on a consensus how to approach this and likely substantial development work to implement.  Depending on the approach chosen the AC-Style might provide some useful ground work - see https://github.com/gravitystorm/openstreetmap-carto/issues/3880#issuecomment-1560964205
- [ ] _disentangling the use of blue and purple color in the style_, currently blue colors are used very non-systematically for various often unrelated features (transport symbols - #3631, several different kinds of water related symbols, cycleways, water lines and polygons).  And the use of purple for admin boundaries (#3489) is constraining us quite massively in improving consistency of our color scheme.  Requires working on consensus.  Solving this would facilitate addressing a large number of issues, in particular
  * #1224
  * #1748
  * #1781
  * #1793
  * #1934
  * #3461
  * #3670
  * #3896
  * #3895 
- [ ] _developing a data preprocessing strategy_, needed in particular for getting rid of the remaining non-OSM data - see #2172, requires working on a consensus how to approach this.
- [ ] _developing a strategy on rendering of explicit and implicit road access restrictions_, #214, requires working on a consensus how to approach this - depending on the outcome of this could mean major cartographic redesign of the roads rendering, in particular needed for consistently depicting road mapping differentiated by means of transport (like cycling roads, bus only roads etc.)

Much of this has _consensus building_ as the main first prerequisite.  See also #3951.

**Comment by imagico** [comment]
I have marked

* developing a strategy on rendering of explicit and implicit road access restrictions
* the move to the flex backend

as done.  In both cases this is just the first step - we have #5027 for further steps regarding the flex backend and database layout.  And we still need to work out the details on our overall strategy regarding access restrictions.  #4952 has defined the rough direction, but details like in #5025, #4321 and more generally matter of dealing with exceptions for explicit or implicit restrictions (like pedestrian roads where bicycles are allowed) still need discussion and decisions to be made.
